obstacle_range: 2.0
raytrace_range: 2.5
footprint: [[-0.15, -0.20], [-0.15, 0.20], [0.15, 0.20], [0.15, -0.20]]
inflation_radius: 0.5
cost_scaling_factor: 3.0
map_type: costmap
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}