footprint: [[-0.15, -0.20], [-0.15, 0.20], [0.15, 0.20], [0.15, -0.20]]
robot_base_frame: base_link
update_frequency: 10.0
publish_frequency: 10.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 4.0
raytrace_range: 4.5

#layer definitions
static:
    map_topic: map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

inflation:
    inflation_radius: 0.5